language: go
sudo: false

before_install:
  - sudo add-apt-repository ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install solc geth

install:
  - scripts/deps.sh
script:
  - scripts/test.sh