language: go
sudo: false

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get -y update
  - sudo apt-get -y install solc ethereum nodejs npm
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - npm install -g soljitsu

install:
  - scripts/deps.sh ensure

script:
  - scripts/test.sh -v

before_deploy:
  - scripts/release.sh

deploy:
  - provider: releases
    file_glob: true
    file:
      - "build/src/IdentityPromises.sol"
      - "build/abi/IdentityPromises.abi"
      - "build/bin/IdentityPromises.bin"
    skip_cleanup: true
    api_key: "$GIT_RELEASES_API_KEY"
    on:
      tags: true
      branch: master
