language: go
sudo: false

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install nodejs npm
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - npm install -g soljitsu
  - go get golang.org/x/tools/cmd/goimports
  - scripts/helpers/setup-geth-tools.sh /home/travis/bin
  - scripts/helpers/setup-solc.sh /home/travis/bin
  - solc --version
  - abigen --sol contracts/UtilsTest.sol --pkg check --out /dev/null

install:
  - scripts/deps.sh ensure

script:
  - scripts/test.sh -v
  - scripts/check_goimports.sh

before_deploy:
  - scripts/release.sh

deploy:
  - provider: releases
    file:
      #MystToken for testnet
      - "build/src/MystToken.sol"
      - "build/abi/MystToken.abi"
      - "build/bin/MystToken.bin"
      #Payments
      - "build/src/IdentityPromises.sol"
      - "build/abi/IdentityPromises.abi"
      - "build/bin/IdentityPromises.bin"
    skip_cleanup: true
    api_key: "$GIT_RELEASES_API_KEY"
    on:
      tags: true
      branch: master
