language: go
sudo: false

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get -y update
  - sudo apt-get -y install solc geth

install:
  - scripts/deps.sh
script:
  - scripts/test.sh